#!/usr/bin/env bash
# prints Best School 10 times but at the 9th iteration displays 9
x=1
while [ $x -ne 11 ]
do 
  if [ $x -eq 9 ]
  then
     echo "Hi"
  else
     echo "Best School"
  fi
  x=$(( x + 1))
done
